### PR TITLE
Move to using pungi for the sample and snakemake CLI management code.

### PR DESCRIPTION
**Pull request by LeeBergstrand**
- Moved `dataset.py`, `run.py`, `sample.py`, and `utils.py` to pungi (https://github.com/rotary-genomics/pungi)
- Import functionality from pungi
- Update README.md install install instructions.

### CODE REVIEW

**Comment by LeeBergstrand** [comment]
@jmtsuji Once we add pungi to Conda, it should simplify the installation. For now, the only way to install it is manually. Once it's in conda or pip, we can add it to `enviroment.yml`, etc.

**Comment by LeeBergstrand** [comment]
@jmtsuji Passed my end-to-end tests.

**Review by jmtsuji — APPROVED** [review]
@LeeBergstrand Looks great to me -- thanks for updating the install in the README as well. Agreed, we can simplify the install once a conda install of pungi is available, but until then, the new install still seems quite straightforward. Feel free to merge this PR. 👍

**Comment by LeeBergstrand** [comment]
Great!

**Pull request merged**
