### PR TITLE
delete requirement to check for other polca files.

### PR DESCRIPTION
**Pull request by LeeBergstrand**
I ran into this error where Polca wouldn't find the files:

- {sample}_polypolish.fasta.unSorted.sam"
- {sample}_polypolish.fasta.alignSorted.bam"

The polca folder has the other files created by the polca run but not these. Does the newer version of Polca not produce these files? Either way, none of these files are used by the follow-on steps, so I removed them from the required outputs.

### CODE REVIEW

**Comment by jmtsuji** [comment]
@LeeBergstrand Interesting that those files were not generated for you. I wonder if we could add a code block like the following to `shell` in that rule, so that those files are deleted, if they are made?

(`polypolish_sam` and `polypolish_bam` would be moved to params)
```bash
if [[ -f {params.polypolish_sam} ]]; then
  rm {params.polypolish_sam}
fi

if [[ -f {params.polypolish_bam} ]]; then
  rm {params.polypolish_bam}
fi
```
This code could be added underneath the final `cd` in the `shell` block. Thoughts?

**Comment by jmtsuji** [comment]
From @LeeBergstrand in #102 :

> POLCA leaves an entire folder full of output files not specified in the rule output. I'm considering having it delete its entire folder using temp. See: https://github.com/rotary-genomics/rotary/issues/92

Agreed that just specifying the whole output directory as a temp file might work really well, given that the output files from this rule might be a bit unstable. Shall we pursue this option?

**Comment by LeeBergstrand** [comment]
@jmtsuji Added code to delete the entire polca directory between runs: https://github.com/rotary-genomics/rotary/commit/e8e237555cc9cfbb44f9906c6822534e685dc105

There was an issue where if polca were rerun on a prior run's data with an existing polca folder, then it would cause errors like the above.

**Comment by jmtsuji** [comment]
@LeeBergstrand This makes sense -- thanks!

**Pull request merged**
