### PR TITLE
Minor README updates

### PR DESCRIPTION
**Pull request by jmtsuji**
Minor updates to reflect the new filtration report (from #126 ) and to highlight both the utilities + workflow aspects of rotary (only the workflow aspect was showcased well in the previous README).

### CODE REVIEW

**Comment by jmtsuji** [comment]
@LeeBergstrand I made some improvements to the README docs -- mind taking a look? Thanks!

**Comment by LeeBergstrand** [comment]
@jmtsuji https://github.com/rotary-genomics/rotary/pull/128 rewrote a few sections in this pull request. Feel free to leave comments about them in that pull request. Once those changes are moved in I will approve this pull request.

**Review by LeeBergstrand — APPROVED** [review]

**Comment by LeeBergstrand** [comment]
@jmtsuji Feel free to merge.

**Comment by jmtsuji** [comment]
@LeeBergstrand Done - thanks!

**Pull request merged**
